type Pagination = struct {
  offset: u32,
  limit: u32,
};

constructor {
  New : ();
};

service AccessControl {
  GrantRole : (role_id: [u8, 32], target_account: actor_id) -> null;
  GrantRolesBatch : (role_ids: vec [u8, 32], target_account: actor_id) -> null;
  RenounceRole : (role_id: [u8, 32], account_id: actor_id) -> null;
  RevokeRole : (role_id: [u8, 32], target_account: actor_id) -> null;
  RevokeRolesBatch : (role_ids: vec [u8, 32], target_account: actor_id) -> null;
  SetRoleAdmin : (role_id: [u8, 32], new_admin_role_id: [u8, 32]) -> null;
  query GetMemberRoleCount : (member_id: actor_id) -> u32;
  query GetMemberRoles : (member_id: actor_id, query: opt Pagination) -> vec [u8, 32];
  query GetRoleAdmin : (role_id: [u8, 32]) -> [u8, 32];
  query GetRoleCount : () -> u32;
  query GetRoleMemberCount : (role_id: [u8, 32]) -> u32;
  query GetRoleMembers : (role_id: [u8, 32], query: opt Pagination) -> vec actor_id;
  query GetRoles : (query: opt Pagination) -> vec [u8, 32];
  query HasRole : (role_id: [u8, 32], account_id: actor_id) -> bool;

  events {
    RoleGranted: struct {
      role_id: [u8, 32],
      target_account: actor_id,
      sender: actor_id,
    };
    RoleRevoked: struct {
      role_id: [u8, 32],
      target_account: actor_id,
      sender: actor_id,
    };
    RoleAdminChanged: struct {
      role_id: [u8, 32],
      previous_admin_role_id: [u8, 32],
      new_admin_role_id: [u8, 32],
      sender: actor_id,
    };
  }
};

