constructor {
  New : ();
};

service AccessControl {
  /// Grants `role_id` to `target_account`.
  /// 
  /// If `target_account` had not been already granted `role_id`, emits a `RoleGranted`
  /// event.
  /// 
  /// Requirements:
  /// 
  /// - the caller must have `role_id`'s admin role.
  GrantRole : (role_id: [u8, 32], target_account: actor_id) -> null;
  /// Grants `role_ids` to `target_account`.
  /// 
  /// If `target_account` had not been already granted any of the `role_ids`,
  /// emits a `RoleGranted` event for each newly granted role.
  /// 
  /// Requirements:
  /// 
  /// - the caller must have the admin role for all specified `role_ids`.
  GrantRolesBatch : (role_ids: vec [u8, 32], target_account: actor_id) -> null;
  /// Revokes `role_id` from the calling account.
  /// 
  /// Roles are often managed via `grant_role` and `revoke_role`: this function's
  /// purpose is to provide a mechanism for accounts to lose their privileges
  /// if they are compromised (such as when a trusted device is misplaced).
  /// 
  /// If the calling account had been granted `role_id`, emits a `RoleRevoked`
  /// event.
  /// 
  /// Requirements:
  /// 
  /// - the caller must be `account_id`.
  RenounceRole : (role_id: [u8, 32], account_id: actor_id) -> null;
  /// Revokes `role_id` from `target_account`.
  /// 
  /// If `target_account` had been granted `role_id`, emits a `RoleRevoked` event.
  /// 
  /// Requirements:
  /// 
  /// - the caller must have `role_id`'s admin role.
  RevokeRole : (role_id: [u8, 32], target_account: actor_id) -> null;
  /// Revokes `role_ids` from `target_account`.
  /// 
  /// If `target_account` had been granted any of the `role_ids`,
  /// emits a `RoleRevoked` event for each newly revoked role.
  /// 
  /// Requirements:
  /// 
  /// - the caller must have the admin role for all specified `role_ids`.
  RevokeRolesBatch : (role_ids: vec [u8, 32], target_account: actor_id) -> null;
  /// Sets `new_admin_role_id` as the admin role for `role_id`.
  /// 
  /// Emits a `RoleAdminChanged` event.
  /// 
  /// Requirements:
  /// 
  /// - the caller must have `role_id`'s admin role.
  SetRoleAdmin : (role_id: [u8, 32], new_admin_role_id: [u8, 32]) -> null;
  /// Returns the admin role ID that controls `role_id`.
  query GetRoleAdmin : (role_id: [u8, 32]) -> [u8, 32];
  /// Returns the number of roles in the system.
  query GetRoleCount : () -> u32;
  /// Returns the role ID at the specified index.
  query GetRoleId : (index: u32) -> opt [u8, 32];
  /// Returns the member at the specified index in the specified role.
  query GetRoleMember : (role_id: [u8, 32], index: u32) -> opt actor_id;
  /// Returns the number of members in the specified role.
  query GetRoleMemberCount : (role_id: [u8, 32]) -> u32;
  /// Returns `true` if `account_id` has been granted `role_id`.
  query HasRole : (role_id: [u8, 32], account_id: actor_id) -> bool;

  events {
    RoleGranted: struct {
      role_id: [u8, 32],
      target_account: actor_id,
      sender: actor_id,
    };
    RoleRevoked: struct {
      role_id: [u8, 32],
      target_account: actor_id,
      sender: actor_id,
    };
    RoleAdminChanged: struct {
      role_id: [u8, 32],
      previous_admin_role_id: [u8, 32],
      new_admin_role_id: [u8, 32],
      sender: actor_id,
    };
  }
};

