[package]
name = "test-bin"
version.workspace = true
authors.workspace = true
edition.workspace = true
homepage.workspace = true
license.workspace = true
repository.workspace = true
rust-version.workspace = true

[dependencies]
# Sails dependencies.
sails-rs.workspace = true

# Local dependencies.
awesome-sails-services = { workspace = true, features = ["all", "test"] }

[build-dependencies]
# Sails dependencies.
sails-client-gen.workspace = true
sails-idl-gen.workspace = true
sails-rs = { workspace = true, features = ["wasm-builder"] }

# Local dependencies.
awesome-sails-services = { workspace = true, features = ["all", "test"] }

[features]
wasm-binary = []
