// Code generated by sails-client-gen. DO NOT EDIT.
#[allow(unused_imports)]
use sails_rs::{client::*, collections::*, prelude::*};
pub struct MsgTrackerTestClientProgram;
impl sails_rs::client::Program for MsgTrackerTestClientProgram {}
pub trait MsgTrackerTestClient {
    type Env: sails_rs::client::GearEnv;
    fn dynamic_counter(
        &self,
    ) -> sails_rs::client::Service<dynamic_counter::DynamicCounterImpl, Self::Env>;
    fn fixed_counter(
        &self,
    ) -> sails_rs::client::Service<fixed_counter::FixedCounterImpl, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MsgTrackerTestClient
    for sails_rs::client::Actor<MsgTrackerTestClientProgram, E>
{
    type Env = E;
    fn dynamic_counter(
        &self,
    ) -> sails_rs::client::Service<dynamic_counter::DynamicCounterImpl, Self::Env> {
        self.service(stringify!(DynamicCounter))
    }
    fn fixed_counter(
        &self,
    ) -> sails_rs::client::Service<fixed_counter::FixedCounterImpl, Self::Env> {
        self.service(stringify!(FixedCounter))
    }
}
pub trait MsgTrackerTestClientCtors {
    type Env: sails_rs::client::GearEnv;
    #[allow(clippy::new_ret_no_self)]
    #[allow(clippy::wrong_self_convention)]
    fn new(self) -> sails_rs::client::PendingCtor<MsgTrackerTestClientProgram, io::New, Self::Env>;
}
impl<E: sails_rs::client::GearEnv> MsgTrackerTestClientCtors
    for sails_rs::client::Deployment<MsgTrackerTestClientProgram, E>
{
    type Env = E;
    fn new(self) -> sails_rs::client::PendingCtor<MsgTrackerTestClientProgram, io::New, Self::Env> {
        self.pending_ctor(())
    }
}

pub mod io {
    use super::*;
    sails_rs::io_struct_impl!(New () -> ());
}

pub mod dynamic_counter {
    use super::*;
    pub trait DynamicCounter {
        type Env: sails_rs::client::GearEnv;
        fn clear_dynamic(&mut self) -> sails_rs::client::PendingCall<io::ClearDynamic, Self::Env>;
        fn confirm_increment(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::ConfirmIncrement, Self::Env>;
        fn request_increment(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RequestIncrement, Self::Env>;
        fn update_dynamic(
            &mut self,
            id: MessageId,
            status: OpStatus,
        ) -> sails_rs::client::PendingCall<io::UpdateDynamic, Self::Env>;
        fn get_status(
            &self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env>;
        fn get_val(&self) -> sails_rs::client::PendingCall<io::GetVal, Self::Env>;
    }
    pub struct DynamicCounterImpl;
    impl<E: sails_rs::client::GearEnv> DynamicCounter
        for sails_rs::client::Service<DynamicCounterImpl, E>
    {
        type Env = E;
        fn clear_dynamic(&mut self) -> sails_rs::client::PendingCall<io::ClearDynamic, Self::Env> {
            self.pending_call(())
        }
        fn confirm_increment(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::ConfirmIncrement, Self::Env> {
            self.pending_call((id,))
        }
        fn request_increment(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RequestIncrement, Self::Env> {
            self.pending_call(())
        }
        fn update_dynamic(
            &mut self,
            id: MessageId,
            status: OpStatus,
        ) -> sails_rs::client::PendingCall<io::UpdateDynamic, Self::Env> {
            self.pending_call((id, status))
        }
        fn get_status(
            &self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env> {
            self.pending_call((id,))
        }
        fn get_val(&self) -> sails_rs::client::PendingCall<io::GetVal, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ClearDynamic () -> ());
        sails_rs::io_struct_impl!(ConfirmIncrement (id: MessageId) -> ());
        sails_rs::io_struct_impl!(RequestIncrement () -> MessageId);
        sails_rs::io_struct_impl!(UpdateDynamic (id: MessageId, status: super::OpStatus) -> bool);
        sails_rs::io_struct_impl!(GetStatus (id: MessageId) -> Option<super::OpStatus>);
        sails_rs::io_struct_impl!(GetVal () -> u32);
    }
}

pub mod fixed_counter {
    use super::*;
    pub trait FixedCounter {
        type Env: sails_rs::client::GearEnv;
        fn clear_fixed(&mut self) -> sails_rs::client::PendingCall<io::ClearFixed, Self::Env>;
        fn confirm_increment(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::ConfirmIncrement, Self::Env>;
        fn remove_fixed(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::RemoveFixed, Self::Env>;
        fn request_increment(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RequestIncrement, Self::Env>;
        fn update_fixed(
            &mut self,
            id: MessageId,
            status: OpStatus,
        ) -> sails_rs::client::PendingCall<io::UpdateFixed, Self::Env>;
        fn get_status(
            &self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env>;
        fn get_val(&self) -> sails_rs::client::PendingCall<io::GetVal, Self::Env>;
    }
    pub struct FixedCounterImpl;
    impl<E: sails_rs::client::GearEnv> FixedCounter for sails_rs::client::Service<FixedCounterImpl, E> {
        type Env = E;
        fn clear_fixed(&mut self) -> sails_rs::client::PendingCall<io::ClearFixed, Self::Env> {
            self.pending_call(())
        }
        fn confirm_increment(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::ConfirmIncrement, Self::Env> {
            self.pending_call((id,))
        }
        fn remove_fixed(
            &mut self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::RemoveFixed, Self::Env> {
            self.pending_call((id,))
        }
        fn request_increment(
            &mut self,
        ) -> sails_rs::client::PendingCall<io::RequestIncrement, Self::Env> {
            self.pending_call(())
        }
        fn update_fixed(
            &mut self,
            id: MessageId,
            status: OpStatus,
        ) -> sails_rs::client::PendingCall<io::UpdateFixed, Self::Env> {
            self.pending_call((id, status))
        }
        fn get_status(
            &self,
            id: MessageId,
        ) -> sails_rs::client::PendingCall<io::GetStatus, Self::Env> {
            self.pending_call((id,))
        }
        fn get_val(&self) -> sails_rs::client::PendingCall<io::GetVal, Self::Env> {
            self.pending_call(())
        }
    }

    pub mod io {
        use super::*;
        sails_rs::io_struct_impl!(ClearFixed () -> ());
        sails_rs::io_struct_impl!(ConfirmIncrement (id: MessageId) -> bool);
        sails_rs::io_struct_impl!(RemoveFixed (id: MessageId) -> Option<super::OpStatus>);
        sails_rs::io_struct_impl!(RequestIncrement () -> MessageId);
        sails_rs::io_struct_impl!(UpdateFixed (id: MessageId, status: super::OpStatus) -> bool);
        sails_rs::io_struct_impl!(GetStatus (id: MessageId) -> Option<super::OpStatus>);
        sails_rs::io_struct_impl!(GetVal () -> u32);
    }
}
#[derive(PartialEq, Clone, Debug, Encode, Decode, TypeInfo)]
#[codec(crate = sails_rs::scale_codec)]
#[scale_info(crate = sails_rs::scale_info)]
pub enum OpStatus {
    Pending,
    Completed,
}
