name: CI

on:
  push:
    branches: [master]
    paths:
      - '.cargo/**'
      - '.github/workflows/**'
      - 'crates/**'
      - 'tests/**'
      - 'benchmarks/**'
      - 'utils/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - 'rustfmt.toml'
      - '!**.md'
  pull_request:
    paths:
      - '.cargo/**'
      - '.github/workflows/**'
      - 'crates/**'
      - 'tests/**'
      - 'benchmarks/**'
      - 'utils/**'
      - 'Cargo.lock'
      - 'Cargo.toml'
      - 'rust-toolchain.toml'
      - 'rustfmt.toml'
      - '!**.md'
  workflow_call:
    inputs:
      ref:
        description: "Git ref to checkout"
        required: false
        type: string

concurrency:
  group: ${{ github.workflow }}-${{ github.ref }}
  cancel-in-progress: true

env:
  CARGO_TERM_COLOR: always

jobs:
  main:
    name: Main CI
    runs-on: ubuntu-latest

    steps:
      - name: Checkout Code
        uses: actions/checkout@v4
        with:
          ref: ${{ inputs.ref }}

      - name: Setup Environment
        uses: ./.github/actions/setup-gear

      - name: Check formatting
        run: cargo fmt --all -- --check

      - name: Check clippy
        run: cargo clippy --workspace --all-targets --all-features -- -D warnings

      - name: Run tests
        run: cargo test --workspace